baseURL = 'https://ezrichards.github.io'
languageCode = 'en-US'
title = 'Ethan Richards'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 2

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 3

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 4

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
